# Generated by Django 4.2.3 on 2024-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appusers_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='adress',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
