# Generated by Django 4.2.3 on 2024-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appusers_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
