# Generated by Django 4.2.3 on 2024-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
