# Generated by Django 4.2.3 on 2024-01-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_announcement_isread_announcement_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUsers',
            new_name='AppUser',
        ),
        migrations.CreateModel(
            name='ReadAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
        ),
    ]
