# Generated by Django 4.0.5 on 2024-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_readannouncement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
