# Generated by Django 4.0.5 on 2024-06-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_appuser_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('itemControlled', models.CharField(max_length=255)),
                ('classWantedToApply', models.CharField(max_length=255)),
                ('isread', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
