# Generated by Django 4.0.5 on 2024-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='room',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
