# Generated by Django 4.0.5 on 2024-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_states_humidity_states_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='states',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
