# Generated by Django 4.0.5 on 2024-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_alter_states_humidity_alter_states_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='states',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
