# Generated by Django 4.0.5 on 2024-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0005_alter_states_humidity_alter_states_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='door',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='pincode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
