# Generated by Django 4.0.5 on 2024-04-04 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0006_states_door_states_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='pincode',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
