# Generated by Django 4.0.5 on 2024-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0007_alter_states_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='mode',
            field=models.CharField(choices=[('Smart Mode', 'Smart Mode'), ('User Mode', 'User Mode'), ('Assisted Mode', 'Assisted Mode')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
