# Generated by Django 4.0.5 on 2024-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0008_states_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='channelOn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='states',
            name='fanLevel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
