# Generated by Django 4.0.5 on 2024-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lightDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDay', models.TimeField(auto_now=True)),
                ('temperature', models.FloatField()),
                ('dayOfWeek', models.DateField(auto_now=True)),
                ('weatherConditions', models.CharField(max_length=50)),
                ('motionDetection', models.CharField(max_length=50)),
                ('LightIntensity', models.FloatField()),
            ],
        ),
    ]
