# Generated by Django 4.0.5 on 2024-03-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightdataset',
            name='dayOfWeek',
            field=models.IntegerField(),
        ),
    ]
