# Generated by Django 4.0.5 on 2024-04-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0004_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
