# Generated by Django 4.0.5 on 2024-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0005_alter_weatherdata_day_alter_weatherdata_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
