# Generated by Django 4.0.5 on 2024-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0006_alter_weatherdata_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
