# Generated by Django 4.0.5 on 2024-05-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0008_alter_weatherdata_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDay', models.TimeField(auto_now=True)),
                ('dayOfWeek', models.IntegerField()),
                ('channelOn', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
