# Generated by Django 4.0.5 on 2024-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0009_tvdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvdataset',
            name='motionDetection',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
