# Generated by Django 4.0.5 on 2024-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0011_alter_tvdataset_dayofweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='person_count',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='motionDetection',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
