# Generated by Django 4.0.5 on 2024-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0012_remove_weatherdata_person_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='outside_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outside_luminosity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outside_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
