# Generated by Django 4.0.5 on 2024-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthomeDataSets', '0013_alter_weatherdata_outside_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='fanLevel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
